### ISSUE TITLE
Error in desktop file

### ISSUE THREAD

**Issue by probonopd** [sudo-give-me-coffee/PhotoGIMP#1]
The desktop file has an error:

`gimp.desktop: error: value "?????????;?????????;????;??????;????????" for locale string list key "Keywords[mr]" in group "Desktop Entry" does not have a semicolon (';') as trailing character`

Please test with a `desktop-file-validate` version that comes with Ubuntu 16.04 or earlier. Thanks.

Reference:
https://github.com/AppImage/appimage.github.io/pull/1461

**Comment by sudo-give-me-coffee** [comment]
Sorry for taking time to respond, i fixed it, apparently is a trouble with original GIMP desktop file.

Can i close the issue?

**Comment by sudo-give-me-coffee** [comment]
I'll close this issue, if the repository still has something wrong, please reopen it
