### ISSUE TITLE
AppImage filename is missing the version number

### ISSUE THREAD

**Issue by probonopd** [sudo-give-me-coffee/PhotoGIMP#4]
AppImage filename is missing the version number. This is annoying especially for users who like to keep around multiple versions, which AppImage allows one to easily do. Also, please do not rename the file that comes out of `appimagetool`, since that **breaks** the delta binary update mechanism.

**Comment by sudo-give-me-coffee** [comment]
In case i really need a fixed name, upload 2 files is a problem?

**Comment by probonopd** [comment]
You could upload both, but may I ask why you need a fixed name?

**Comment by sudo-give-me-coffee** [comment]
I have an article marked read-only (this is done automatically after a period of time) on plus.diolinux.com with a direct download link
